### ISSUE TITLE
Feed discovery broken.

### ISSUE THREAD

**Issue by kevincox** [murrple-1/rss_temple#36]
I tried two URLs and got different results.

https://kevincox.ca returned "No feed detected" and "Could not find feed exposed in supplied URL".

https://kevincox-test.blogspot.com/feeds/posts/default resulted in the API endpoint returning 404.

**Comment by murrple-1** [comment]
The first one is due to https://github.com/murrple-1/rss_temple/blob/master/api/exposed_feed_extractor.py#L85 not catching the `<link href="/feed.atom" rel="alternate" title="Blog Posts" type="application/atom+xml">` tag, so that should be easy to fix.

The second one I will have to deep dive to see what's going on.

Cheers!

**Comment by kevincox** [comment]
https://feedmail.org/ also hit a 404 error that looked similar to the blogspot one.

**Comment by murrple-1** [comment]
Fixed in https://github.com/murrple-1/rss_temple_ui/commit/28e3a973833c82593a812846d9b6d8d48a1ead3c
